// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKT8Yt-DnGJLWzAdS7FuydyqzmZFtT43o',
    appId: '1:314589508448:web:579ccb9db27854354aa405',
    messagingSenderId: '314589508448',
    projectId: 'papers-automation',
    authDomain: 'papers-automation.firebaseapp.com',
    storageBucket: 'papers-automation.firebasestorage.app',
    measurementId: 'G-FRP7TN265G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKp1H7RH8f7t3Dlb9YS8d_NpDycw4BeMU',
    appId: '1:314589508448:android:8dd744c195d995b44aa405',
    messagingSenderId: '314589508448',
    projectId: 'papers-automation',
    storageBucket: 'papers-automation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFkFeFsUGyTRwZ06U7w4G1D49QlVqeHX4',
    appId: '1:314589508448:ios:a119a7c98f15931a4aa405',
    messagingSenderId: '314589508448',
    projectId: 'papers-automation',
    storageBucket: 'papers-automation.firebasestorage.app',
    iosBundleId: 'com.example.paperauto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFkFeFsUGyTRwZ06U7w4G1D49QlVqeHX4',
    appId: '1:314589508448:ios:a119a7c98f15931a4aa405',
    messagingSenderId: '314589508448',
    projectId: 'papers-automation',
    storageBucket: 'papers-automation.firebasestorage.app',
    iosBundleId: 'com.example.paperauto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKT8Yt-DnGJLWzAdS7FuydyqzmZFtT43o',
    appId: '1:314589508448:web:161439508d1a6a204aa405',
    messagingSenderId: '314589508448',
    projectId: 'papers-automation',
    authDomain: 'papers-automation.firebaseapp.com',
    storageBucket: 'papers-automation.firebasestorage.app',
    measurementId: 'G-84Q2DGYXWY',
  );
}
